name: C# Generator Integration Test

on:
  push:
    branches: [ main ]
    paths:
      - 'internal/generators/csharp/**'
      - 'cmd/generate.go'
      - 'test/csharp-integration/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'internal/generators/csharp/**'
      - 'cmd/generate.go'
      - 'test/csharp-integration/**'

jobs:
  csharp-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Run C# integration test
        run: ./test/csharp-integration/test-compilation.sh